data:
  image: cogniteev/echo:latest
  volumes:
   - /var/www:/var/www
   - /var/lib/mysql

db:
  image: mariadb:latest
  ports:
   - "3306:3306"
  volumes_from:
   - data
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=user
   - MYSQL_PASSWORD=user
   - MYSQL_DATABASE=fireside

web:
  build: .
  links:
   - db
  ports:
   - "80:80"
   - "443:443"
  volumes_from:
   - data
